apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: '{{ template "azure-clientid-syncer-webhook.name" . }}'
    azure-clientid-syncer-webhook.io/system: "true"
    chart: '{{ template "azure-clientid-syncer-webhook.name" . }}'
    release: '{{ .Release.Name }}'
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  name: azure-clientid-syncer-webhook-admin
  namespace: '{{ .Release.Namespace }}'
