apiVersion: v1
data:
  {{ if .Values.config.azure.enabled }}
  PROVIDER_TYPE: azure
  AZURE_AUTHORITY_HOST: {{ .Values.config.azure.environment | default "AzurePublicCloud" }}
  AZURE_TENANT_ID: {{ required "A valid .Values.config.azure.tenantID entry required!" .Values.config.azure.tenantID }}
  AUTO_DETECT_OIDC_ISSUER_URL: {{ .Values.config.azure.autoDetectOidcIssuerUrl | default "true" }}
  {{ if .Values.config.azure.oidcIssuerUrl }}
  OIDC_ISSUER_URL: {{ .Values.config.azure.oidcIssuerUrl }}
  {{ end }}
  {{ end }}
  {{ if .Values.config.gcp.enabled }}
  PROVIDER_TYPE: gcp
  GCP_PROJECT_ID: {{ required "A valid .Values.config.gcp.projectID entry required!" .Values.config.gcp.projectID }}
  {{ end }}
  FILTER_TAGS: {{ .Values.config.filterTags | default "" }}
  CLUSTER_IDENTIFIER: {{ .Values.config.clusterIdentifier | default "" }}
kind: ConfigMap
metadata:
  labels:
    app: '{{ template "azure-clientid-syncer-webhook.name" . }}'
    azure-clientid-syncer-webhook.io/system: "true"
    chart: '{{ template "azure-clientid-syncer-webhook.name" . }}'
    release: '{{ .Release.Name }}'
  name: azure-clientid-syncer-webhook-config
  namespace: '{{ .Release.Namespace }}'
