apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    app: '{{ template "azure-clientid-syncer-webhook.name" . }}'
    azure-clientid-syncer-webhook.io/system: "true"
    chart: '{{ template "azure-clientid-syncer-webhook.name" . }}'
    release: '{{ .Release.Name }}'
  name: azure-clientid-syncer-webhook-manager-role
  namespace: '{{ .Release.Namespace }}'
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
