apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    aks.clientid.syncer/use: "true"
  name: testsa
---
apiVersion: v1
kind: Pod
metadata:
  name: quick-start
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: testsa
  containers:
    - image: ghcr.io/azure/azure-workload-identity/msal-go
      name: oidc
      env:
      - name: KEYVAULT_URL
        value: <keyvault-url>
      - name: SECRET_NAME
        value: <secret-name>
  nodeSelector:
    kubernetes.io/os: linux