# Default values for azure-clientid-syncer-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
image:
  repository: ghcr.io/shiftavenue/azure-clientid-syncer
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # release: 0.0.37
imagePullSecrets: []
nodeSelector:
  kubernetes.io/os: linux
resources:
  limits:
    cpu: 500m
    memory: 400Mi
  requests:
    cpu: 500m
    memory: 300Mi
tolerations: []
affinity: {}
service:
  type: ClusterIP
  port: 443
  targetPort: 9443
azureEnvironment: AzurePublicCloud
# enter your tenant ID here. If you leave this empty, the webhook will try to auto-detect the tenant ID.
config:
  azureTenantID: ""
  autoDetectOidcIssuerUrl: "true"
  oidcIssuerUrl: ""
  filterTags: ""
  clusterIdentifier: ""
webhook:
  timeoutSeconds: 15
metricsAddr: ":8095"
metricsBackend: prometheus
logLevel: 0
priorityClassName: system-cluster-critical
mutatingWebhookAnnotations: {}
# e.g. using azure workload identity with this webhook by by enabling it via label:
# azure.workload.identity/use: "true"
podLabels: {}
podAnnotations: {}
mutatingWebhookNamespaceSelector: {}
# minAvailable and maxUnavailable are mutually exclusive
podDisruptionBudget:
  minAvailable: 1
  # maxUnavailable: 0
serviceAccount:
  # e.g. using azure workload identity with this service by setting the client ID and tenant ID:
  # azure.workload.identity/client-id: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
  # azure.workload.identity/tenant-id: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
  annotations: {}
