name: Release Charts

on:
  create:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Replace version
        run: |
          cd charts/azure-clientid-syncer-webhook
          sed -i "s@version:.*@version: ${{ github.ref }}@g" Chart.yaml
          cat Chart.yaml

#      - name: Configure Git
#        run: |
#          git config user.name "$GITHUB_ACTOR"
#          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
#
#      - name: Run chart-releaser
#        uses: helm/chart-releaser-action@v1.5.0
#        env:
#          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"