name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/push-helm.yaml"
      - "charts/**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Replace version
        run: |
          RELEASE_VERSION=$(gh release view --jq '.name[1:]' --json name)
          cd charts/azure-clientid-syncer-webhook
          sed -i "s@appVersion:.*@appVersion: $RELEASE_VERSION@g" Chart.yaml
          cat Chart.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"